name: Validate Gradle Wrapper

on: 
  - push
  - pull_request

jobs:
  gradle-wrapper-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Validation
        uses: gradle/wrapper-validation-action@v1
